### ISSUE TITLE
Indifference to table borders and padding

### ISSUE THREAD

**Issue by plaindocs** [wooorm/remark-lint#110]
I filed https://github.com/coala/coala-bears/issues/1008 because I'd like to not care about table cells, ie, let them have pipe borders or not. 

Looking at:

https://github.com/wooorm/remark-lint/blob/master/doc/rules.md#table-pipes

> Options: string, either 'consistent', 'padded', or 'compact', default: 'consistent'.

but can I disable the rule entirely?

Thanks

**Comment by wooorm** [comment]
Sure, yes you can. Passing `false`, `0`, or `'off'` to `table-pipes` should turn the rule off. Read more about it in the into: https://github.com/wooorm/remark-lint/blob/master/doc/rules.md#list-of-rules.

**Comment by wooorm** [comment]
@plaindocs were you able to turn it off?

**Comment by wooorm** [comment]
This should work. Could you raise a new issue or ask on Gitter if it doesn’t?
