### ISSUE TITLE
Some configuration comments don't work

### ISSUE THREAD

**Issue by EvgenyOrekhov** [wooorm/remark-lint#112]
I want to disable the "list-item-content-indent" rule for the whole file, but I can't:

```js
var report = require('vfile-reporter');
var remark = require('remark');
var lint = require('remark-lint');

var file = remark()
    .use(lint, {listItemContentIndent: true})
    .process(`
<!--lint disable list-item-content-indent-->
1. **Fork**
2. **Clone**

        git clone https://github.com/<your-username>/lints.git
3. **Configure remotes**

        cd lints
        git remote add upstream https://github.com/EvgenyOrekhov/lints.git
`);

report(file);
```

It still says "Don’t use mixed indentation for children, remove 1 space".

This example at RunKit: https://runkit.com/57e78997c63d1e1400b5bd9f/584325903d46300014bb185f

**Comment by wooorm** [comment]
Thanks for the detailed question, problem, and the runkit.

Block-level HTML needs a blank line between it and the next thing. Sorry about that. I’ve added a mention in the docs!
