### ISSUE TITLE
no-consecutive-blank-lines: Allow padding before headings

### ISSUE THREAD

**Issue by verekia** [wooorm/remark-lint#116]
This is a direct extension of #115 (feel free to close it if this one is more relevant).

It is a common stylistic practice to leave padding before headings (or "at the end of sections", depending on how you see it).

I would like to propose an option for the `no-consecutive-blank-lines` to accept this stylistic choice (using ipsum for a more realistic content):

```
<!-- Beginning of the file, with empty first line -->

# Main Title

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non ipsum vitae augue vehicula tincidunt tincidunt ut sapien. Vestibulum felis nisi, egestas quis ultrices at, gravida at ex.
Sed vitae tristique lectus. Nulla sodales neque ut tortor blandit molestie. Mauris interdum vulputate feugiat. Proin eleifend dignissim pulvinar. Nam elementum dapibus placerat.
Vivamus commodo ex quis blandit rutrum. Nunc euismod volutpat tortor, nec pharetra urna ultricies in.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non ipsum vitae augue vehicula tincidunt tincidunt ut sapien. Vestibulum felis nisi, egestas quis ultrices at, gravida at ex.
Sed vitae tristique lectus. Nulla sodales neque ut tortor blandit molestie. Mauris interdum vulputate feugiat. Proin eleifend dignissim pulvinar. Nam elementum dapibus placerat.
Vivamus commodo ex quis blandit rutrum. Nunc euismod volutpat tortor, nec pharetra urna ultricies in.


## Section A

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non ipsum vitae augue vehicula tincidunt tincidunt ut sapien. Vestibulum felis nisi, egestas quis ultrices at, gravida at ex.
Sed vitae tristique lectus. Nulla sodales neque ut tortor blandit molestie. Mauris interdum vulputate feugiat. Proin eleifend dignissim pulvinar. Nam elementum dapibus placerat.
Vivamus commodo ex quis blandit rutrum. Nunc euismod volutpat tortor, nec pharetra urna ultricies in.


## Section B

[...]
```

This helps visualizing sections tremendously and makes markdown files much prettier in my opinion.

Consecutive lines that appear in other places than before headings should still trigger warnings of course. What do you think?

**Comment by wooorm** [comment]
If we do that, we should split it. Maybe like this:

* Extra spacing between heading and preceding content (similar to [remark-heading-gap](https://github.com/ben-eb/remark-heading-gap), but in lint form, possibly an extension of `no-consecutive-blank`);
* `no-initial-lines` (separate from `no-consecutive-blank`, so it can be turned off);
* `no-final-lines` (separate from `no-consecutive-blank`, so it can be turned off).

**Comment by verekia** [comment]
I'm not sure I understand `no-initial-lines` and `no-final-lines`, could you elaborate about what would these 2 do?

**Comment by wooorm** [comment]
I propose:

* `no-consecutive-blank-lines`, to check spacing between nodes. It could have a an option for extra spacing before headings;
* `no-initial-blank-lines`, to check that there’s no spacing before the first node (separate so it can be 
controlled separately);
* `no-final-blank-lines`, to check that there’s no spacing after the last node (separate so it can be controlled separately).

Does that make it clearer?

**Comment by verekia** [comment]
Yes it does, thanks!

**Comment by wooorm** [comment]
I think this would be a good addition as an external rule! If anyone would like to take this up, I’d be able to help, but unfortunately I’m not able to do this myself.

❤️

**Comment by wooorm** [comment]
Whoops, sorry! I forgot about GH-115.
Are you still interested in helping?

**Comment by verekia** [comment]
I'm also quite overwhelmed these days, so I can't help unfortunately. Feel free to close my issues :)

**Comment by wooorm** [comment]
Cheers @verekia!
