### ISSUE TITLE
Webpack cannot compile remark-lint

### ISSUE THREAD

**Issue by Sarah-Seo** [wooorm/remark-lint#117]
I know this library is for node.js. But, I need this for browser to show warnings.

Although I've already checked the code, I'm still confused about where should I fix.

1. Fix webpack configuration
2. Fix remark-lint
3. Fix npm-prefix or load-plugin

This is the error message from webpack.

```
WARNING in ./~/load-plugin/index.js
36:9 Critical dependency: the request of a dependency is an expression

ERROR in ./~/rc/index.js
Module parse failed: /Users/sarah-seo/Code/Inpad/node_modules/rc/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
| var cc   = require('./lib/utils')
| var join = require('path').join
 @ ./~/npm-prefix/index.js 3:9-22
 @ ./~/load-plugin/index.js
 @ ./~/remark-lint/lib/index.js
 @ ./~/remark-lint/index.js
 @ ./src/lib/markdown.js
```

**Comment by wooorm** [comment]
This seems to stem from [rc](https://github.com/dominictarr/rc), which does have a [`browserify`](https://github.com/dominictarr/rc/blob/132062de0e61881a025cc4784d9a2798409c2bf1/package.json#L6) field. Is it possible to support those in webpack?

**Comment by wooorm** [comment]
@Sarah-Seo Ping!

**Comment by Sarah-Seo** [comment]
Sorry, I forgot to answer.
Yes, It seems to be possible. 👍 I'll try it.
https://github.com/webpack/docs/wiki/configuration#resolvepackagemains

**Comment by Sarah-Seo** [comment]
```
WARNING in ./~/load-plugin/index.js
36:9 Critical dependency: the request of a dependency is an expression
```
It is compiled anyway. But I got the critical warning.
I think **loading all plugins** should be done **while compiling**.

I'm afraid it would requires some drastic changes

**Comment by wooorm** [comment]
> loading all plugins should be done while compiling

To my knowledge, that’s what happens. But I’m guessing that as the code is still included, webpack warns.

> I'm afraid it would requires some drastic changes

I think a fix could be to expose the same interface in `load-plugin` when in the browser, but exposing functions that throw an error instead of trying to require something?

**Comment by wooorm** [comment]
Could you try if the [`browser`](https://github.com/wooorm/load-plugin/tree/browser) branch of `load-plugin` works?

**Comment by Sarah-Seo** [comment]
I don't know how to replace the branch. So, I just download it and replace all scripts.

**Comment by wooorm** [comment]
Yeah that should work to.
What I mostly do is git clone the project, and checkout the branch. Then, I use [`npm link`](https://docs.npmjs.com/cli/link) from the project, and `npm link load-plugin` from the project I want it into.

**Comment by Sarah-Seo** [comment]
Thanks for your comment! Compiling didn't return any critical messages.
I'll inform you again after I actually implement this feature to my app. 👍

**Comment by wooorm** [comment]
Alright, I pushed 2.1.0 of load-plugin, which includes this fix. Thanks for helping Sarah!
