### ISSUE TITLE
Implement cache

### ISSUE THREAD

**Issue by evilebottnawi** [wooorm/remark-lint#120]
That would be great, at the moment only `eslint` have `cache`, in `stylelint` we working at this https://github.com/stylelint/stylelint/issues/2270 :+1:

**Comment by wooorm** [comment]
Hi @evilebottnawi! 👋

That’s interesting, but something that should’t be here. I think [unified-engine](https://github.com/wooorm/unified-engine) is the best place for it. If you want, you can open an issue over there, though, it’s not very high on my list of things to do, but maybe someone else can chip in!
