### ISSUE TITLE
Any possible way to warn without failing?

### ISSUE THREAD

**Issue by sobolevn** [wooorm/remark-lint#121]
I am trying to show an issue about a custom lint rule. But I don't want to fail the test because of that.
Is it even possible?

What have I tried: https://github.com/wemake-services/remark-lint-are-links-valid/blob/master/lib/are-links-valid.js#L10

I'm trying to use `file.message()` but it is not working for me.

**Comment by wooorm** [comment]
Could it be that the [boolean just never come through](https://github.com/wooorm/remark-lint/blob/master/doc/external.md#synchronous)?

**Comment by wooorm** [comment]
@sobolevn Ping!

**Comment by sobolevn** [comment]
I will pong you back on holidays, sorry for the delay.

**Comment by wooorm** [comment]
I think this problem has to do with `boolean`s values: you cannot accept `false` or `true` in your options. I suggest using an object instead.

If it’s another issue, could you ping below or open a new one?
