### ISSUE TITLE
"1:1  error  Cannot process specified file: it’s ignored" with remark@3

### ISSUE THREAD

**Issue by jeddy3** [wooorm/remark-lint#130]
Hello.

Given the following [lerna](https://github.com/lerna/lerna) directory structure:

```
packages
  package1 
    node_modules
    package.json
    README.md 
  package2
    node_modules
    package.json
    README.md
.gitignore
.remarkrc
package.json
README.md
```

Where `.remarkrc` contains:

```json
{
  "plugins": [
    "preset-lint-recommended",
    "preset-lint-consistent"
  ]
}
```

And the _root_ `package.json` contains:

```json
{
  "scripts": {
    "lint:md": "remark '**/*.md' --ignore-path .gitignore --quiet --frail",
  },
  "devDependencies": {
    "remark-cli": "3.0.0",
    "remark-preset-lint-consistent": "2.0.0",
    "remark-preset-lint-recommended": "2.0.0",
  }
}
```

And `.gitignore` contains:

```
.DS_Store
.env
dist
lerna-debug.log
node_modules
npm-debug.log
coverage
```

Running `npm run lint:md` returns a few thousand of the same error (I believe one for each markdown files within the `node_modules` directories, e.g.:

```console
packages/website/node_modules/leveldown/README.md
  1:1  error  Cannot process specified file: it’s ignored
```

Whereas the same setup (albeit with a `remark-cli@2` configuration object) threw no errors. 

I've taken a poke around, but I'm struggling to see what might be causing it. Am I missing something obvious?

**Comment by wooorm** [comment]
The previous version did some magic things there, which caused [problems](https://github.com/unifiedjs/unified-engine/issues/2).

Thing is that your globs match those files, and your ignore file says to ignore them. remark doesn’t know what to do in that case, so it warns.

Is there any reason not to pass `.` instead of the glob? A different file-finding mechanism kicks in then, which should work properly!

**Comment by jeddy3** [comment]
> Is there any reason not to pass `.` instead of the glob?

Nope, no particular reason. Using `.` worked great. Thank you :)

**Comment by wooorm** [comment]
Great. Sure no problem, thanks for using remark!

**Comment by theetrain** [comment]
I am also facing this issue. Given there are changes in `.github/ISSUE_TEMPLATE/defect_template.md`, I have:

**.remarkignore**

```
.github/ISSUE_TEMPLATE/**
```

When running `remark --quiet --frail .`, I also see the error:

```sh
.github/ISSUE_TEMPLATE/defect_template.md
1:1  error  Cannot process specified file: it’s ignored
```
