### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by jasonLaster** [wooorm/remark-lint#137]
Hi, have you considered adding tests for the various packages?

I'm asking because I think it would be easy to include fixtures for the different cases you would test for each package. 

If you're interested I'd be happy to help and set something up that's similar to [prettier](https://github.com/prettier/prettier/tree/master/tests).

**Comment by wooorm** [comment]
Hi @jasonLaster, welcome.

Every rule is tested and their coverage is checked too, this is [included in the badges and Travis](https://github.com/wooorm/remark-lint/blob/ec6810703dd629c87f9add557eaf3f65a4dcbb2b/test.js#L240-L259). Tests are run based on the [JSDoc comments](https://github.com/wooorm/remark-lint/blob/ec6810703dd629c87f9add557eaf3f65a4dcbb2b/packages/remark-lint-rule-style/index.js#L14-L44) inside each file.

> If you're interested I'd be happy to help and set something up that's similar to prettier.

I like xo :) I’m fine with prettier but I don’t really see a reason in changing code-style.
