### ISSUE TITLE
relation to markdownlint?

### ISSUE THREAD

**Issue by wbolster** [wooorm/remark-lint#140]
can you describe the relation to `markdownlint` (which has both a ruby and nodejs version... quite confusing).

or, phrased differently, why should i use this awesome tool and not any others?

thanks in advance!

**Comment by wooorm** [comment]
> The relation to markdownlint

The relation? They’re all markdown linters! :p

> Which has both a ruby and nodejs version... quite confusing

They’re two projects by different people, I think. The JS version came later, and tried to adhere to the Ruby version’s warnings.

> Why should i use this awesome tool and not any others?

I like remark-lint, remark-lint is also part of a much bigger ecosystem ([remark](https://github.com/wooorm/remark)). But I suggest you try them all out!

**Comment by wbolster** [comment]
thanks. this only becomes useful for me when integrated into flycheck, which is something i might look into next when i find some spare time. :)
