### ISSUE TITLE
Example .remarkrc

### ISSUE THREAD

**Issue by dionlarson** [wooorm/remark-lint#142]
Can you link to an example `.remarkrc` for `remark-lint`? I cannot get any errors to trigger with `remark-cli` or `linter-remark`. I'm trying to build out the rules listed [here](https://github.com/MakeSchool-Tutorials/Tutorial-Template/blob/master/.remarkrc) but I have tried simpler rulesets as well.

### .remarkrc
```
{
    "plugins": {
        "remark-lint": {
              "maximum-line-length": ["error", 80]
        }
    }
}
```

### invalid.md
```
# Hello

This is a line that is way too long. It goes over 80 characters which is a bit much for a line.
```

### Output
```
$ DEBUG="*" remark .
  unified-engine:configuration Looking for `.remarkrc,.remarkrc.js,.remarkrc.yml,.remarkrc.yaml` configuration files +0ms
  unified-engine:configuration Looking for `remarkConfig` fields in `package.json` files +2ms
  unified-engine:find-up No files found for `/Users/dion/Desktop/testing-remark` +5ms
  unified-engine:file-set-pipeline:stdin Ignoring `streamIn` +2ms
  unified-engine:file-pipeline:read Reading `/Users/dion/Desktop/testing-remark/invalid.md` in `utf8` +1ms
  unified-engine:file-pipeline:read Read `/Users/dion/Desktop/testing-remark/invalid.md` (err: null) +1ms
  unified-engine:find-up Read file `/Users/dion/Desktop/testing-remark/.remarkrc` +5ms
  unified-engine:file-pipeline:configure Using settings `{}` +0ms
  unified-engine:file-pipeline:configure Using `1` plugins +0ms
  unified-engine:file-pipeline:configure Using plug-in `lint`, with options `{"maximum-line-length":["error",80]}` +0ms
  unified-engine:file-pipeline:parse Parsing `invalid.md` +0ms
  unified-engine:file-pipeline:parse Parsed document +9ms
  unified-engine:file-pipeline:transform Transforming document `invalid.md` +1ms
  unified-engine:file-pipeline:transform Transformed document (error: null) +1ms
  unified-engine:file-pipeline:queue Queueing `invalid.md` +0ms
  unified-engine:file-pipeline:queue `invalid.md` can be flushed +0ms
  unified-engine:file-pipeline:queue Flushing: all files can be flushed +0ms
  unified-engine:file-pipeline:stringify Not compiling document without output settings +0ms
  unified-engine:file-pipeline:copy Not copying +0ms
  unified-engine:file-pipeline:stdout Ignoring writing to `streamOut` +0ms
  unified-engine:file-pipeline:file-system Ignoring writing to file-system +1ms
invalid.md: no issues found
```

**Comment by wooorm** [comment]
That’s probably ’cause you’re used to the old remark-lint! There were some changes in 6.0.0 and you can find them on [GH Releases (with examples)](https://github.com/wooorm/remark-lint/releases).

:wave:

**Comment by dionlarson** [comment]
Ah, I see now. Commenting this in case anyone comes across the same issue (there are no specific `.remarkrc` examples in the releases page.

### Working .remarkrc for 6.0.0
```
{
    "plugins": {
        "remark-lint-maximum-line-length": ["error", 80]
    }
}
```

In this case, you'll need `remark-lint-maximum-line-length` installed. Given the complexity of my linked `.remarkrc`, I will be taking the "create your own plugin" route.

Thanks @wooorm !

**Comment by asbjornu** [comment]
More information on the configuration of individual plugins for both JSON and YAML would be warmly welcome. I'm probably just blind, but I haven't seen `"remark-lint-maximum-line-length": ["error", 80]` anywhere else than in this issue.

**Comment by wooorm** [comment]
@asbjornu It’s explain in the rules section: https://github.com/remarkjs/remark-lint/blob/main/doc/rules.md#configuration

**Comment by asbjornu** [comment]
@wooorm, the examples are only given for a JavaScript configuration (not JSON or YAML) and does not cover all plugins, afaict?

**Comment by wooorm** [comment]
Indeed. JS kinda equals how JSON/YAML work too, just the different syntax because of the different languages.

Each rule can be configured the same way, except that they all have different options: `blockquote-indentation` has none, `maximum-line-length` accepts a number, yet others accept an object. Those are described in each rule.

**Comment by asbjornu** [comment]
I found it a bit confusing and hard to understand, that's all. I may not be alone with that experience. It's not obvious that these are equivalent and all working (afaict), imho:

```js
remark()
  .use(require('remark-lint-maximum-line-length'), ['error', 70])
```

```json
"remark-lint-maximum-line-length": ["error", 70]
```

```yaml
- remark-lint-maximum-line-length: 70
```
