### ISSUE TITLE
no-blockquote-without-caret misnomer

### ISSUE THREAD

**Issue by boneskull** [wooorm/remark-lint#143]
I think `no-blockquote-without-caret` needs to be renamed.  Sorry if this has been brought up already.

A [caret](https://en.wikipedia.org/wiki/Caret) is `^`.  

`>` is an ["angle bracket" or "chevron"](https://en.wikipedia.org/wiki/Bracket).

**Comment by wooorm** [comment]
Oh no, you’re right! Are you interested in creating a PR for that?

**Comment by wooorm** [comment]
[Published](https://www.npmjs.com/package/remark-lint-no-blockquote-without-marker)!
