### ISSUE TITLE
A new rule for line break style

### ISSUE THREAD

**Issue by kachkaev** [wooorm/remark-lint#145]
It'd be great to have a rule to checks consistency of `\n` vs `\n\r` in the end of lines, similarly to eslint's [`linebreak-style`](http://eslint.org/docs/rules/linebreak-style).

LF is allowed, CRLF throws an error:
```js
 "remarkConfig": {
    "plugins": ["remark-preset-linebreak-style", "unix"]
  }
```

CRLF is allowed, LF throws an error:
```js
 "remarkConfig": {
    "plugins": ["remark-preset-linebreak-style", "windows"]
  }
```

Both CRLF and LF are allowed (the rule is off):
```js
 "remarkConfig": {
    "plugins": ["remark-preset-linebreak-style", false]
  }
```

What do you guys think of adding this? I can consider crafting a PR, but it'd be great if someone more knowledgeable overtook me, because figuring out the internals of the library for a newbie like me will take some time.

**Comment by kachkaev** [comment]
Yay! Many thanks @wooorm, I'm looking forward to try this!

**Comment by wooorm** [comment]
:+1:

Will try to do some more stuff before I publish a new version!

**Comment by wooorm** [comment]
Released!
