### ISSUE TITLE
remarkConfig override problem

### ISSUE THREAD

**Issue by ThomDietrich** [wooorm/remark-lint#146]
Hello @wooorm,
here's a shortened form of my configuration:

```json
"dependencies": {
  "remark-cli": "^3.0.1",
  "remark-lint-table-pipe-alignment": "^1.0.0",
  "remark-lint-unordered-list-marker-style": "^1.0.0",
  "remark-preset-lint-consistent": "^2.0.0",
  "remark-preset-lint-markdown-style-guide": "^1.0.0",
  "remark-preset-lint-recommended": "^2.0.0"
},
"remarkConfig": {
  "plugins": [
    ["remark-preset-lint-consistent", true],
    ["remark-preset-lint-recommended", true],
    ["remark-preset-lint-markdown-style-guide", true],
    ["remark-lint-unordered-list-marker-style", "-"],
    ["remark-lint-table-pipe-alignment", false]
  ]
}
```

The idea is the following: Use the consistent, recommended and style-guide rules, if rules reappear, override their setting. So far so good. I then added further overrides as can be seen with the marker-style example. Also works as expected.

My problem is with the last line where I want to disable the overly restrictive pipe-alignment rule. This is not working. I'm still seeing:

```
    46:47-46:48  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  46:231-46:232  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  46:297-46:298  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    47:39-47:40  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    47:79-47:80  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  47:406-47:407  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
```

The setting doesn't seem to have an effect but it has. Upon setting it to true the linting result becomes:

```
    46:47-46:48  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    46:47-46:48  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  46:231-46:232  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  46:231-46:232  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  46:297-46:298  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  46:297-46:298  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    47:39-47:40  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    47:39-47:40  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    47:79-47:80  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
    47:79-47:80  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  47:406-47:407  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
  47:406-47:407  warning  Misaligned table fence                                table-pipe-alignment         remark-lint
```

Seems like the setting is not overwritten and the true adds a second execution of the one rule. Can you make any sense of it?

Best! Thomas

**Comment by ThomDietrich** [comment]
I've just deleted `node_modules` and installed everything anew (`npm install`). The problem is now solved to me but there must be a reason for this.

**Comment by wooorm** [comment]
I’m guessing you had some old versions of plugins? I think npm sometimes adds old versions if you have them cached, maybe that’s it?

**Comment by ThomDietrich** [comment]
I thought so too and did a `npm cache clean && npm restart && npm install && npm update` (might be too much, I'm not fluent in node). Didn't change anything.

Besides I've been working on another system yesterday and today. Even the cached version would be one day old...

**Comment by wooorm** [comment]
Oh, I don’t know exactly what’s going on but I have to remove `node_modules` and `npm install` quite often to fix bugs, so I’m pretty sure this is npm. Your code looks fine, and as a new install works, I’m going to close this!

Cheers,
Titus

**Comment by ThomDietrich** [comment]
This workaround did the trick but this honestly doesn't seem like a solution. I'd recommend to at least add a note about this to documentation!! 

Thanks for this great tool and your prompt helpful answers! 😉🍻

**Comment by wooorm** [comment]
> This workaround did the trick but this honestly doesn't seem like a solution. I'd recommend to at least add a note about this to documentation!!

I get your frustration, but I don’t think it’s a “workaround”, I think it’s a bug with npm. I’ve noticed it with ESLint too, and other projects. Many issues I get are fixed by “turning it off and on again”, and I don’t think it’s scalable to add to all repo’s I maintain.

**Comment by unicornware** [comment]
@wooorm 

what do you suggest if "turning it off and on again" does **not** work?

i've tried doing so, as well as suggestions from #165 (even though i have everything locally installed), but i'm still unable to override plugin settings.

the configuration below does not work. i even tried with `.remarkrc.mjs`.

```json
  "type": "module",
  "remarkConfig": {
    "plugins": [
      "@flex-development/remark-preset",
      ["remark-lint-maximum-heading-length", 130]
    ]
  },
  "devDependencies": {
    "@flex-development/remark-preset": "1.0.0",
    "remark-cli": "12.0.1",
    "remark-lint-maximum-heading-length": "4.1.1"
  },
  "resolutions": {
    "remark-lint-maximum-heading-length": "4.1.1"
  },
  "packageManager": "yarn@4.12.0"
```

i can't reconfigure `remark-lint-maximum-heading-length`, nor can i disable it.

i can only use ignore comments &mdash; 32 of them to be exact &mdash; to get rid of false warnings.

**Comment by wooorm** [comment]
That looks good, thought it depends what’s in your own preset package?
A small repro would help.
You could run “npm why remark-lint-maximum-heading-length“ to see if there are different copies, and why
