### ISSUE TITLE
Could not find module `preset-lint-recommended` using .remarkrc and Atom

### ISSUE THREAD

**Issue by jamesbeldock** [wooorm/remark-lint#147]
I use Atom and linter-markdown. I have a simple `~/.remarkrc` file:

```
{
  "plugins": [
    "preset-lint-recommended",
    ["remark-lint-list-item-indent", false],
    ["remark-lint-list-item-bullet-indent", false]

  ],
  "settings": {
    "commonmark": true
  }
}
```

Whenever the package loads, I get an error in the console indicating that the `preset-lint-recommended` module cannot be loaded:

```
Error: Could not find module `preset-lint-recommended`
  at addModule (/Users/foo/.atom/packages/linter-markdown/node_modules/unified-engine/lib/configuration.js:232:35)
```

Help appreciated on what is wrong with my config.  Thank you!

Versions:  Atom 1.18.0
Linter-markdown: 4.0.1 using AtomLinter

**Comment by wooorm** [comment]
You probably want to install those modules referenced in `.remarkrc` locally. Or you can go with globally installed modules, I just pushed better support for that, but it requires some set-up on your part, as can be seen it the [soon-to-be readme of `linter-remark`](https://github.com/AtomLinter/linter-markdown/blob/6422e6c27fece814ad2457e2e6cea368bd3708f0/README.md).

Could you open further issues with `linter-markdown` on its issue tracker?

Hope this helps, cheers,
Titus
