### ISSUE TITLE
Add support for TOML frontmatter

### ISSUE THREAD

**Issue by plaindocs** [wooorm/remark-lint#149]
A popular static site generate Hugo, has an option for [TOML](https://gohugo.io/content/front-matter/#toml-example) front matter:

```
+++
title = "spf13-vim 3.0 release and new website"
description = "spf13-vim is a cross platform distribution of vim plugins and resources for Vim."
tags = [ ".vimrc", "plugins", "spf13-vim", "vim" ]
date = "2012-04-06"
categories = [
  "Development",
  "VIM"
]
slug = "spf13-vim-3-0-release-and-new-website"
+++
Content of the file goes Here
```

Which isn't supported by remark-lint:

```
diff --git 
index 8ecfdee..af60f1d 100644
@@ -1,9 +1,9 @@
-+++
+\+++
 title = "Step Definitions Orig"
 menu = "gherkin"
-+++
+\+++
```

As the parser ignores the front matter, I think this should be an easy fix?

**Comment by plaindocs** [comment]
Thank you @wooorm !

**Comment by wooorm** [comment]
P.S. If you run into plugins that don’t support TOML nodes, raise issues on their repo’s and we’ll figure out how to support them!
