### ISSUE TITLE
Question/Suggestion: Pre-configured linter

### ISSUE THREAD

**Issue by andywer** [wooorm/remark-lint#152]
Is there a pre-configured linter available like the famous `standard` or `xo` for linting JS?

I think not having to pick the rules yourself makes adoption much simpler and gives you the confidence that people who are really into this have picked those rules according to best practices.

Btw, great work 😊

**Comment by wooorm** [comment]
No there’s not, feel free to do that!

There are presets, like the [markdown style guide](https://github.com/wooorm/remark-lint/tree/master/packages/remark-preset-lint-markdown-style-guide). That’s pretty close to someone thinking about it and picking sensible configuration. Or [make your own](https://github.com/search?utf8=✓&q=remark-preset&type=Repositories)!
