### ISSUE TITLE
Links in sublists are not registered

### ISSUE THREAD

**Issue by ostrokach** [wooorm/remark-lint#157]
I get a `Found unused definition (remark-lint:no-unused-definitions)` error with the following markdown. Any ideas?

```markdown
1.  Short description

    Long description

    a.  Subsection

        Long description [link]

[link]: http://google.com
```

Error message:

```text
  9:1-9:26  warning  Found unused definition  no-unused-definitions  remark-lint

⚠ 1 warning
```

**Comment by wooorm** [comment]
Hi Alexey, thanks for using `remark-lint`!

You can’t use letters to make “ordered” lists in markdown. What you have here is a list, where the “Long description [link]” is a code-block.

See [astexplorer](https://astexplorer.net/#/gist/ef8b2757603a3aa9cc1f3af75c662acf/9c72eecbf522afcbdfc83240c337cfad56f624ac) for how this is seen in markdown.

👋
