### ISSUE TITLE
Possible typos in rules' docs

### ISSUE THREAD

**Issue by vsemozhetbyt** [wooorm/remark-lint#158]
Some rule descriptions have cryptic fragments "When turned on is passed in":

https://github.com/wooorm/remark-lint/search?utf8=%E2%9C%93&q=%22When+turned+on+is+passed+in%22&type=

It seems some invalid examples were intended but forgotten in the https://github.com/wooorm/remark-lint/commit/4a380fca274bd25c6298725a6812a20b4cd065b5

**Comment by wooorm** [comment]
Thank you! Should be much better now!
