### ISSUE TITLE
Update REAMDE: chcokr/mdast-lint-sentence-newline -> remark

### ISSUE THREAD

**Issue by chcokr** [wooorm/remark-lint#37]

**Comment by wooorm** [comment]
Working on this as we speak :)

**Comment by dirk-thomas** [comment]
The commit only changes the label but not the URL itself. Should the URL be updated too?

**Comment by chcokr** [comment]
GitHub redirects to the new URL, but I still agree with @dirk-thomas that the URL should be updated too.

**Comment by wooorm** [comment]
Oh, whoops, forgot about that. Thanks for mentioning!
