### ISSUE TITLE
remarkrc not overriding defaults

### ISSUE THREAD

**Issue by pcgilday** [wooorm/remark-lint#43]
Upgraded to 2.3.0 and getting warnings about maximum-line-length in spite of it being set to false in the ```.remarkrc```, shown below. Set this from false to 100 and I get two warnings from the same line that it exceeds 80 (default) and 100 (my setting). 

```
{
  "plugins": {
    "lint": {
        "maximum-line-length": 100
    }
  },
  "settings": {
    "commonmark": true
  }
}
```

![image](https://cloud.githubusercontent.com/assets/6249643/12789969/11e288cc-ca6e-11e5-9ac7-19b6356967fb.png)

**Comment by wooorm** [comment]
Darn. Are you on the latest remark, remark-lint? Could you share the doc you’re working with?

**Comment by wooorm** [comment]
P.S. are guessing the exact version of remark-lint is `2.3.1`, right?

**Comment by pcgilday** [comment]
Yes, latest for remark (3.2.2). Happens with 2.3.0 and 2.3.1.

**Comment by pcgilday** [comment]
I do not know about sharing the README, it is in a private repo. I could reproduce with non-sensitive README if you need it.

**Comment by wooorm** [comment]
I’m using the following now (107 chars):

```md
alpha bravo charlie delta echo foxtrot golf hotel india juliett kilo lima mike november oscar papa quebec.
```

I’m guessing I don’t need your README. Otherwise, i’ll request a non-sensitive one :)

**Comment by pcgilday** [comment]
# Test markdown

Here is some test markdown that has really long lines to show that the maximum-line-length setting is not being overridden.

Copying this into a md file and running the specified versions with the specified remarkrc will reproduce the error.

**Comment by wooorm** [comment]
Could you post the results of running remark with that example? I get the feeling my test set-up is showing good results?!

**Comment by wooorm** [comment]
I get:

```text
example.md
      3:124  warning  Line must be at most 100 characters  maximum-line-length
      5:117  warning  Line must be at most 100 characters  maximum-line-length

⚠ 2 warnings
```

...with your code. Which is what’s expected from the `.remarkrc` you provided. Can you show me how you execute remark?

**Comment by pcgilday** [comment]
![image](https://cloud.githubusercontent.com/assets/6249643/12790566/dac73fa6-ca70-11e5-8f33-6f8889f97f2a.png)

**Comment by wooorm** [comment]
Can you show me how you run remark? I’m guessing this is like GH-42.

P.S. as a potential solution: remove all `node_modules/` and re-executre `npm install`

**Comment by SpainTrain** [comment]
`.remarkrc`

```json
{
  "plugins": {
    "lint": {
        "maximum-line-length": false
    }
  },
  "settings": {
    "commonmark": true
  }
}
```

Here is how it is invoked:

`package.json`

```json
  "scripts": {
    "lint-remark": "remark -f -u remark-lint fixtures/*.md app/**/*.md *.md",
```

We run linting on CI, so every build deletes `node_modules` and `npm install`s `=-)` (this was caught by greenkeeper)

We will continue digging on our end as well to see if we can find the cause.

**Comment by wooorm** [comment]
Oh okay, thanks @SpainTrain.

First weird thing: the first `.remarkrc` (start of this thread) includes a line-length of `100`, not `false`, whereas your example does show `false`.

Second weird thing: Mike, you’re using `lint` in both the `.remarkrc` *and* on the CLI (`-u lint`). You should drop the latter as that includes the plug-in twice (see GH-42, maybe I *do* have to make that more clear...)

Also: are you two working on the same project or is this happening in multiple places?

Thanks for your patience!

**Comment by pcgilday** [comment]
@wooorm Same project, our setting is false, but it is easier to see the true problem when it is set to 100 (as this shows duplicate warnings for the same line.

**Comment by SpainTrain** [comment]
> You should drop the latter

That fixes it.  Thanks Titus!  (note to self Read The Fun Manual :grin: )

**Comment by pcgilday** [comment]
Thanks @wooorm and @SpainTrain :+1:

**Comment by wooorm** [comment]
Pfew, great. Thanks for mentioning it though, I was resisting making this more clear but now I’m sure I should.

Could you help me with one last thing? How can I make it more clear in this project’s README that, when using a [`.remarkrc`](https://github.com/wooorm/remark-lint#configuring-remark-lint), you shouldn’t specify `-u lint`?

**Comment by SpainTrain** [comment]
IMO the simplest and most effective would just be adding a CLI example to the `Configuring remark-lint` section, with a little explanation above or below it explaining that `-u` is not needed.

**Comment by SpainTrain** [comment]
happy to PR also =-)

**Comment by wooorm** [comment]
If you’re interested in PRing, awesome!

I’d say:

* Use the same example code as in `Command line`;
* Show a `.remarkrc` with `list-item-indent: false` and `maximum-line-length: 100`;
* Show how to run that (`remark example.md`);
* Show the output (same as in `Command line`, but without the line about list-item-indent)?

The `maximum-line-length` does not occur in the example, but that’s no problem, it just shows one can set values in `.remarkrc` too.

What do you think?

**Comment by pcgilday** [comment]
Sounds about right, I'll get that updated and submit a PR soon.

**Comment by wooorm** [comment]
:+1:
