### ISSUE TITLE
Output custom severity warnings

### ISSUE THREAD

**Issue by izdi** [wooorm/remark-lint#45]
Is there a way to output custom severity ? At this moment only warnings are available as i can see.
 * along with defining custom rule you could also have a severity type when linter catches it.
 * could it be possible?
This could be helpful for CI.

Thanks!

**Comment by wooorm** [comment]
If you want to fail a CI for lint warnings, you can use the [`--frail`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#-f---frail) option on remark’s CLI.
