### ISSUE TITLE
Remark Lint escapes underscores in emoji

### ISSUE THREAD

**Issue by benbalter** [wooorm/remark-lint#46]
Running remark lint with the default configuration escapes underscores in GitHub-style emoji, e.g., `:heavy_check_mark: `.

Turning on `pedantic` mode, replaces the underscores with the emphasis character, e.g., `:heavy*check*mark:`.

### Steps to reproduce:

1. Create a markdown file with `:heavy_check_mark: `
2. `remark example.md -u remark-lint --output`

### Expected 

File contains  `:heavy_check_mark: `

### Actual

File contains  `:heavy\_check\_mark:`

**Comment by wooorm** [comment]
Hey @benbalter, thanks for raising this issue, and the detail you put
into it :+1:

First, some background. [**remark**](https://github.com/wooorm/remark)
does the markdown parser. It can receive options, for example `gfm`, which
turns on support for tables and strikethrough, which is on by default,
and `pedantic`, which turns off some features available in most modern
markdown implementations, which is off by default.

**remark-lint**, on the other hand, is a plug-in working with **remark**
to highlight possible style violations or mistakes in markdown.

So, when you’re talking about “escapes” in the provided code, you’re
talking about **remark** (as that’s what generates the code).

**A quick solution** might be to turn off pedantic mode. I’m not sure if
that’s possible, but there’s often no need to use it. This would ensure
the underscores in “words” are not seen as emphasis.

Another alternative, which is kind-of hacky, is to set
[`emphasis: '_'`](https://github.com/wooorm/remark/blob/master/doc/remarksetting.7.md#emphasis-markers).

A solution which is in the works is support through
[**remark-gemoji**](https://github.com/jackycute/remark-gemoji/), but that
project is still in the works. What it does is turn `:+1:` into `👍`.
We’re still figuring out what’s needed, and from your code (I see you’re
using remark for [your site](https://github.com/benbalter/benbalter.github.com))
It seems like you just want gemoji shortcode detection, or do you also
want to render as (unicode) emoji, or to HTML images? Could you tell me?

**Comment by benbalter** [comment]
Wow. @wooorm thanks for all the context. Suspected it might have been in remark, but wasn't sure the best place to start. Should I open an issue over on remark?

> A quick solution might be to turn off pedantic mode. I’m not sure if
that’s possible, but there’s often no need to use it. This would ensure
the underscores in “words” are not seen as emphasis.

Turning off pedantic mode is what currently escapes the underscores. Turning it on, replaces whatever the emphasis character is, meaning, you can't have `*` for emphasis and use GitHub-style emoji. You can see [my `.remarkrc` file here](https://github.com/benbalter/dotfiles/blob/master/.remarkrc#L11-L16).

> A solution which is in the works is support through
remark-gemoji, but that
project is still in the works. What it does is turn :+1: into 👍.
We’re still figuring out what’s needed, and from your code (I see you’re
using remark for your site)
It seems like you just want gemoji shortcode detection, or do you also
want to render as (unicode) emoji, or to HTML images? Could you tell me?

I saw remark-gemoji (my first attempt at a fix), but ideally, I'd like to keep the shortcodes in the markdown after linting (with the output flag set to `true`).

If this is a crazy edge case you don't want to support (or I'm doing something terribly wrong), feel free to let me know. Really liking using Remark to fix my Markdown (the primary way I write these days). :smile:

**Comment by wooorm** [comment]
> Should I open an issue over on remark?

You can keep it here, for now, I’ll open things in the correct places :)

> Turning off pedantic mode is what currently escapes the underscores.

You’re right, that wouldn’t work indeed. Sorry!

> ideally, I'd like to keep the shortcodes in the markdown after linting

OK, that sounds like a good use case, not at all edge case. I’ll coordinate with the creator of **remark-gemoji** to finish that project in a way that also enables authors to keep gemoji shortcuts into their documents.

For now, unfortunately, the only way to keep your gemoji shortcuts in place, would be to turn off the `--output` setting.

> Really liking using Remark to fix my Markdown

Thanks, @benbalter, great to hear. Feel free to raise issues or ask me questions. You’re running remark over a huge amount of files, so there’s bound to be some problems, and I’d love to hear your experience and the things you run into.

**Comment by benbalter** [comment]
If it helps, it appears to be more than just emoji, but any word with a mid-word-underscore (e.g., `civic_hackers` (possibly including those in code blocks as well, but I can't seem to recreate it).

**Comment by wooorm** [comment]
`code` (in ticks) shouldn’t have this problem (as it doesn’t need escaping inside), but please share if you find an example of this!

**Comment by wooorm** [comment]
Hey @benbalter, thanks for waiting.

I just pushed [remark@4.1.0](https://github.com/wooorm/remark/releases/tag/4.1.0), which  contains a fix for the escaping of underscores in words. *But only when not in pedantic mode!*.

This also includes your example of `sinatra_auth_github` > `sinatra\_auth\_github`, which now doesn’t cause escapes.

So, could you update to remark@4.1.0, turn off pedantic mode, and let me know if that fixes your problems?

**Comment by benbalter** [comment]
@wooorm :sparkles: That looks like it did it. Thanks again for an awesome project.

**Comment by wooorm** [comment]
Great, good to hear! :)
