### ISSUE TITLE
Multiple lines in table cells

### ISSUE THREAD

**Issue by stueken** [wooorm/remark-lint#50]
There is no rule how to style table cells which have multiple line content. Is it possible to add a rule? All researched solutions use HTML ('br').

**Comment by wooorm** [comment]
There’s no rule because it’s not possible to include lines in cells in markdown, other than the by you proposed solution. I’m not sure what you’d want a rule to do here.

**Comment by stueken** [comment]
I'm relatively new to markdown and try to keep consistent to the rules of remark. I know that markdown is not supporting multiple lines. However, for newbies it is more than helpful when you make a note about this in your rules when people look after it and maybe show a non-standard solution as alternative like the br-rule. Just a thought.
