### ISSUE TITLE
Allow external .remarkrc file to be used

### ISSUE THREAD

**Issue by RichardLitt** [wooorm/remark-lint#57]
Trying to get standard-readme going (again, as always). The remark-lint defaults are great, but I want something a bit more strict. 

Do you have any ideas as to how to use one .remarkrc in a CLI tool for markdown files in directories that can't see that .remarkrc? I think some sort of alias might work, but I'm just wondering if you've thought of this before.

**Comment by wooorm** [comment]
:+1:

Is the [`-c, --config <filePath>`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#-c---config-path-path) option what you’re looking for?

**Comment by RichardLitt** [comment]
It might be. The issue is I'm hoping to have a single command, `standard-readme` or something, and automatically point to that config in the global npm package without requiring the user to type `-c`. This may be really simple with npm and I might just be missing it, I'm not sure.

**Comment by wooorm** [comment]
In that case, I suggest to use the API to create `remark-standard-readme`, which itself [uses `remark-lint` and provides configuration](https://github.com/wooorm/remark-lint/blob/master/doc/api.md#remarkuselint-options).

For example:

```js
var lint = require('remark-lint');

function attacher(remark) {
  remark.use(lint, {
    'emphasis-marker': '*'
    // etc.
  });
}

module.exports = attacher;
```

Then, that plugin can be used like this: `remark -u standard-readme`. And, if you want, you can create a `standard-readme` npm package which executes exactly that.

**Comment by wooorm** [comment]
I think the original question is answered; please open another issue or use the Gitter channel if you need help!
