### ISSUE TITLE
How to quote link-title-style rule in .remarkrc?

### ISSUE THREAD

**Issue by keegoid** [wooorm/remark-lint#59]
For the [link-title-style](https://github.com/wooorm/remark-lint/blob/master/doc/rules.md#link-title-style) rule, I am trying to set the style to the double quote option in the .remarkrc file.

```json
"plugins": {
  "lint": { "link-title-style": '"' }
}
```

[error on Travis-CI](https://travis-ci.org/keegoid/keegoid.github.io/builds/126088881)
[.remarkrc](https://github.com/keegoid/keegoid.github.io/blob/675adafa7d3b8333c14f29f613bd78ad7089c679/.remarkrc)

Thanks for your work on remark! I've been learning a lot about it recently and think it will be useful for supporting markdown standards in public writing.

**Comment by keegoid** [comment]
Testing with:

```json
"plugins": {
  "lint": { "link-title-style": """ }
}
```

Travis errors with [unexpected string](https://travis-ci.org/keegoid/keegoid.github.io/builds/126093435)

**Comment by wooorm** [comment]
It’s [JSON](http://www.json.org), so the following works:

```json
"plugins": {
  "lint": { "link-title-style": "\"" }
}
```
