### ISSUE TITLE
Clarify `list-item-spacing` message

### ISSUE THREAD

**Issue by despairblue** [wooorm/remark-lint#60]
It seems there is no way to satisfy both rules for lists with long lines of am I mistaken?

**Comment by wooorm** [comment]
[`list-item-spacing`](https://github.com/wooorm/remark-lint/blob/master/doc/rules.md#list-item-spacing) has to do with the fact that if a list-item spans multiple lines, it and the following list-item should be joined by an empty line.

**Comment by despairblue** [comment]
Oh, now I get it. I thought it was complaining that I had an item that wasn't starting with a list indicator (`*` or `-`).

What do you think about changing the rules output to something like `Missing new line after multiline list item.`?

**Comment by despairblue** [comment]
edit: `Missing new line after list item.`

Just figured that all list items should be loose.

**Comment by wooorm** [comment]
Agreed, thanks for the suggestion.

I’ll combine this with some more stuff for the next major release, as it’s breaking.

P.S. Are you interested in PRing?

**Comment by despairblue** [comment]
@wooorm I'll put it on my todo list. Can't promise anything, but I'll try!
