### ISSUE TITLE
warnings from no-consecutive-blank-lines 

### ISSUE THREAD

**Issue by keegoid** [wooorm/remark-lint#61]
I keep getting warnings where there are no blank lines. Can't seem to crack this one. 
I could disable in .remarkrc but would like to keep this one enabled.

[Travis-CI build](https://travis-ci.org/keegoid/keegoid.github.io/builds/126145316)

line 10 in: [CONTRIBUTING.md](https://github.com/keegoid/keegoid.github.io/blob/af4c8282efd8972edf79b19577d0e5c41f9a1085/CONTRIBUTING.md)
line 15 in: [README.md](https://github.com/keegoid/keegoid.github.io/blob/af4c8282efd8972edf79b19577d0e5c41f9a1085/README.md)

**Comment by wooorm** [comment]
Sorry, @keegoid, I appreciate you using remark, but I’m not in the habit of debugging other people’s projects. If there’s a problem with remark or remark-lint, I’d like to see it in a small test case which I can run myself.

See [“Contributing to Open Source on GitHub: Create an Issue”](https://guides.github.com/activities/contributing-to-open-source/) for more tips.

**Comment by keegoid** [comment]
I understand and I accept your challenge. ;)

After further analysis, I've determined this to be a perfect storm or combinatorial effect of interactions between remark, remark-lint and the remark-inline-links plugin. I didn't realize this, but the order of plugins listed in the .remarkrc file matters. 

The error disappears when I move the inline-links plugin after the lint plugin. In this way the lint plugin can do it's linting before the other plugins wreak havoc on the markdown. 

The inline-link plugin is doing it's thing on __every other__ referenced link, causing:

1. extra blank lines to be created, which
1. lint then warns about, and 
1. remark then fixes

Thus hiding the issue that lint had just warned about causing me a world of confusion. O_o

(I know the inline-links plugin isn't yours. I'll be working on that issue separately.)

With that crazy explanation, here is the test you can perform on the attached file (extract the zip):

### This generates a warning from no-consecutive-blank-lines

```bash
remark ncbl-test.md --use "inline-links" --use "lint=\"maximum-line-length\": false"
```

### This doesn't generate a warning

```bash
remark ncbl-test.md --use "lint=\"maximum-line-length\": false" --use "inline-links"
```

### And this adds blank lines between the referenced urls

```bash
remark ncbl-test.md
```

If I can fix the inline-links plugin and configure remark not to add blank lines between referenced urls, then I think the problem will be solved. Thoughts?

[ncbl-test.md.zip](https://github.com/wooorm/remark-lint/files/239403/ncbl-test.md.zip)

**Comment by wooorm** [comment]
Thanks @keegoid for the detailed explanation, I really appreciate it a lot!!!

Unfortunately im going on holiday now so it'll take two weeks for me to review :(

**Comment by keegoid** [comment]
No worries, vacation time is important. Don't pay it another thought until you get back. I'll post here if I find anything new.

**Comment by wooorm** [comment]
Digging in! :+1:

**Comment by wooorm** [comment]
I’ll release an update to `inline-links` in a sec. It fixes the problems you outlined above. Please let me know if still run into problems!

**Comment by keegoid** [comment]
Awesome! Thanks @wooorm. It's working well now.

One thing, should remark be adding blank lines between referenced links as it does with `remark ncbl-test.md` in my example above? I kind of prefer having all the links in one group at the bottom (when not using remark with `inline-links`). Though, I'm not sure of the convention here.

**Comment by wooorm** [comment]
Yes it is expected behaviour because those nodes are block level, or rather, inside nodes accepting block level elements. And, those blocks are joined by two newlines when compiling.

I haven't seen much interest in this, but I would accept a PR for this if someone's interested!
