### ISSUE TITLE
Option to enforce a dot at the end of the sentence

### ISSUE THREAD

**Issue by sobolevn** [wooorm/remark-lint#66]
Hi, thanks for your awesome project.

I have a need to enforce the sentences to end with `.` (or any other allowed char). Would this option be helpful? 

Specifically talking about https://github.com/sobolevn/awesome-cryptography and `awesome-lists` in general.

**Comment by wooorm** [comment]
Hi @sobolevn, thanks for using remark.

I like your suggestion but it’s outside of the scope of this project: natural language is quite a big problem, and I don’t believe it should be part of the core. Rather, I suggest creating an [external rule](https://github.com/wooorm/remark-lint#list-of-external-rules).
