### ISSUE TITLE
Lists, check boxes and links

### ISSUE THREAD

**Issue by kachkaev** [wooorm/remark-lint#68]
Not sure that I'm not missing anything, but it looks like I found a bug. Here's a MWE:

```md
* [ ] [example](http://example.com)
  * [ ] test1
  * [ ] test2
```
This rather simple sequence causes of list items brings out the following error: `[remark-lint] [list-item-content-indent] Don’t use mixed indentation for children, add 4 spaces at line 2 col 3` (I'm witnessing it in Atom).

It looks like the parser is confused by the square brackets on line 1 that follow the check box. These tiny changes in the source make the error go away:

```md
* [ ] test
  * [ ] test1
  * [ ] test2
```

```md
* [ ] an [example](http://example.com)
  * [ ] test1
  * [ ] test2
```
Despite that it's easy to get rid of the error with the above changes, I could figure out how keep a link near the top-level check box and not see the linter error. Trying various combinations of spaces around square brackets did not help.

**Comment by wooorm** [comment]
Thanks, it indeed had to do with the algorithm starting at the wrong position and seeing the opening bracket of the link for a checkbox. Cheers!
