### ISSUE TITLE
Skipping warnings on last element of the file

### ISSUE THREAD

**Issue by tsnik** [wooorm/remark-lint#69]
I developed external rule for remark-lint to check punctuation endings. https://github.com/wemake-services/remark-lint-list-item-punctuation
But there is a problem. I call file.warn('Some text', {column, line}). There are no symbols after that position except spaces and newlines. But I don't see any warnings on it as a result.
Does it has to work in that way?

**Comment by wooorm** [comment]
Could you provide the code you use and run to get this problem, and exactly what you expected instead?

I’d love to help but I don’t like putting time into figuring out what you’re exactly asking!

Tip: [GitHub’s guide](https://guides.github.com/activities/contributing-to-open-source/#contributing).

**Comment by tsnik** [comment]
To get this problem:
1. Clone this repo https://github.com/tsnik/skipping-warnings-issue
2. Run npm install
3. Run nodejs index.js
4. You will got this output:
https://gist.github.com/tsnik/1e7744df921223e8676ac1d041814f92

Why there is warning when I look at file.messages in plugin, but there is no warning when I look it in remark result callback?

**Comment by wooorm** [comment]
Ah, thanks for the detailed info, I appreciate it! 👍

I found the problem and have a fix in mind, hang tight!

**Comment by wooorm** [comment]
@tsnik Released in [`remark-message-control@2.0.1`](https://github.com/wooorm/remark-message-control/releases/tag/2.0.1). If you `npm update`, you should see the message appear in the results!

**Comment by tsnik** [comment]
Thanks for quick fix. Now it works fine!
