### ISSUE TITLE
.remarkrc configuration fails if packages have been installed to /node_modules

### ISSUE THREAD

**Issue by rarkins** [wooorm/remark-lint#70]
We are running `remark`/`remark-lint` out of `/node_modules`. Scripts are run from `/src` and `/node_modules/.bin` is added to `$PATH`. Although this is unorthodox, it's completely "legal" as far as I'm aware, and node itself is happy with this and has no problem finding modules or indeed running `remark-lint`. However when I try to add a `plugins.lint` configuration to a `.remarkrc` it shows errors like:

```
1:1  error    Error: Cannot find module 'lint'
```

Would something like this fix it? https://github.com/wooorm/remark-lint/compare/master...rarkins:rarkins-fix-toplevel-modules?expand=1

**Comment by wooorm** [comment]
@rarkins Have you tried using `remark-lint` instead of `lint` as the name?

**Comment by rarkins** [comment]
@wooorm actually you're right - changing `lint` to  `remark-lint` stops the errors. However, unfortunately I can't seem to get the rules to apply though. Should this work to "disable" line length checking?

```json
{
  "plugins": {
    "remark-lint": {
      "maximum-line-length": 99999
    }
  }
}
```

FYI: https://github.com/wooorm/remark-lint/blame/master/readme.md#L97

**Comment by wooorm** [comment]
Passing `false` should be fine. Could you show me exactly how you run the CLI?

**Comment by wooorm** [comment]
Re `lint`, well, that works for most set-ups, but `remark-lint` should work in all cases.

**Comment by rarkins** [comment]
Here's the command I'm running:
```sh
$ remark -u remark-lint config containers docker-images lib scripts *.md
```

**Comment by rarkins** [comment]
By the way, I set it up "normally" on a separate computer just now to eliminate whether the `/node_modules/.bin` path is the problem. i.e `remark` and `remark-lint` are installed globally and then the above command run. Still I seem unable to disable/modify any of the rules, even though the `.remarkrc` is clearly being read

**Comment by rarkins** [comment]
One more copy/paste to show how I'm getting the warnings despite the `.remarkrc` present:
```sh
...
lots of warnings
...
    113:101      warning  Line must be at most 80 characters                      maximum-line-length
    115:157      warning  Line must be at most 80 characters                      maximum-line-length

lib/bricks/index/README.md: no issues found

⚠ 563 warnings
$ cat .remarkrc
{
  "plugins": {
    "remark-lint": {
      "maximum-line-length": false
    }
  }
}
```

**Comment by wooorm** [comment]
Found it, it’s because `lint` is run twice:

See [this section in `readme.md`](https://github.com/wooorm/remark-lint#configuring-remark-lint)

> We now run the below command **without the `-u remark-lint`** since our .remarkrc includes the lint plugin.

What do you get if you omit `-u remark-lint`?

**Comment by rarkins** [comment]
> What do you get if you omit -u remark-lint?

That works. Sorry for the trouble and thanks for the brilliant support.

**Comment by wooorm** [comment]
No problem, thanks for asking. 👍 Don’t hesitate with more Qs. [Gitter](https://gitter.im/wooorm/remark) is also a good place for this!
