### ISSUE TITLE
"plugins.lint" ignored

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark-lint#71]
The documentation says to use "plugins.lint"

If only "plugins.lint" is used in  `.remarkrc`, it is ignored.

If I have `.remarkrc` with both "plugins.lint" (using line length 99) and "plugins.remark-lint" (using line length 100) keys, the errors are duplicated with one showing 99 and the other showing 100

https://travis-ci.org/jayvdb/PocketEuler/jobs/137156450#L928

If only "plugins.remark-lint" is used, the config is used, and there is no error duplication. \o/  So maybe it is just the documentation that needs updating.

**Comment by jayvdb** [comment]
Ugh, this is probably because remark-cli auto-loads remark-lint as `lint`, and then adding `-u remark-lint` (mentioned in the README) loads the plugin a second time?

**Comment by wooorm** [comment]
1) Do not pass a `.remarkrc` if it can be detected.
2) Do not pass `-u remark-lint` if it’s in your config file.

Good luck!

**Comment by jayvdb** [comment]
After browsing the issues I find that a few others have fallen into this trap of ending up with duplicate plugins (#42).  I see the documentation as slightly improved again.

Is it not feasible to at least error when the plugin is being loaded the second time?  Are there plugins where it is sensible to load them twice?
