### ISSUE TITLE
Consider making no-heading-punctuation more specific

### ISSUE THREAD

**Issue by rugk** [wooorm/remark-lint#74]
IMHO it would be useful if `no-heading-punctuation` could only handle dots `.` at the end of a headline.

Because `!` and `?` have legitimate uses. Question marks are especially okay, if you e.g. think of FAQs, where one may use headings for the questions. And exclamation marks also may change the effect/impression of a headline heavily and are therefore [intently used](http://www.easymedia.in/use-punctuation-marks-headlines/).
Here is also a nice article on headlines: http://blog.prleap.com/archives/press-release-optimization-how-to-write-an-effective-headline/
There they however say not to use `!` for headlines. I may agree with that, but at least `?` is completly okay.
BTW you may also find interesting guides there, which you could add to this plugin, such as "One-word headlines are unacceptable."

Only, (and I really thing exclusively) dots [are not suited for headlines](https://english.stackexchange.com/questions/32884/should-i-use-a-period-at-the-end-of-a-headline).

**Comment by wooorm** [comment]
This rule already accepts a list of characters; you can [pass a new list to overwrite this](https://github.com/wooorm/remark-lint/blob/master/doc/rules.md#no-heading-punctuation).

This rule was based on [this rule in markdownlint](https://github.com/mivok/markdownlint/blob/master/docs/RULES.md#md026---trailing-punctuation-in-header).

I suggest passing options in this particular case! And, you can also [create your own rules](https://github.com/wooorm/remark-lint#list-of-external-rules)!
