### ISSUE TITLE
Make `reset` option `true` by default

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/remark-lint#81]
Learn from ESLint. They started out with defaults and a lot later realized that it's much better having everything off by default. Users config become so much more clearer when you can read what rules it uses, instead of what it doesn't.

**Comment by wooorm** [comment]
Yes, seems like a very good idea! This’ll probably be implemented once https://github.com/wooorm/remark/issues/183 lands.

**Comment by wooorm** [comment]
Getting pretty close (by adding presets)! Somewhere this/next week?!
