### ISSUE TITLE
Support string severity in addition to numbers

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/remark-lint#97]
Regarding: https://github.com/wooorm/remark-lint/commit/77709f56ac54c0f73428afc17142395f5cdca271

It's a lot more user-friendly. See how it's done with ESLint: https://github.com/sindresorhus/eslint-config-xo/blob/f61e5fec28b7691471075b0c41862a7286e8726d/index.js#L19

**Comment by wooorm** [comment]
👍

Very logical extension of 77709f5 indeed.

I dislike `warn` though, preferring `'off'`, `'on'`, `'error'` instead. That way, the three levels are:

* `0`, `false`, `'off'`;
* `1`, `true`, `'on'`;
* `2`, `'error'`.

**Comment by sindresorhus** [comment]
That would make it worse. There's no clear distinction between `on` and `error`.

**Comment by wooorm** [comment]
I feel something for both, so I added them both as well.
Do keep in mind string severities must be wrapped in an array, currently, as it’ll be a breaking change to support strings without being wrapped.
