### ISSUE TITLE
Allow severity to be specified without array if there are no options

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/remark-lint#98]
Regarding: https://github.com/wooorm/remark-lint/commit/77709f56ac54c0f73428afc17142395f5cdca271

Before:

``` json
{
  "final-newline": [0]
}
```

After:

``` json
{
  "final-newline": 0
}
```

This is how ESLint does it.

**Comment by wooorm** [comment]
Current behaviour is to handle values that are neither array nor boolean as the `options` instead:

```js
{
  listItemIndent: 'space'
}
```

Say this was added, it would interfere with some rules, notable those accepting numbers (e.g., [first-heading-level](https://github.com/wooorm/remark-lint/blob/f5b7bd79b9dde770b3a8abecadfa5defaba5f895/doc/rules.md#first-heading-level)).


```js
{
  firstHeadingLevel: 2
}
```

I’m not sure which would be more useful to end users: specifying a value for `firstHeadingLevel` or specifying its severity. I can see where ESLint / you are coming from but to me, `firstHeadingLevel: 2` reads as setting the options and not the severity.

**Comment by kgryte** [comment]
I agree with @wooorm on this.

```
{
  firstHeadingLevel: 2
}
```
reads as setting the options and not the severity. I would rather the behavior stays as is.

**Comment by wooorm** [comment]
Hey! I don’t feel the need to change the current system.

If you’re using a JavaScript config file you could always do something like this:

```js
module.exports = expand({
  firstHeadingLevel: 2
})

function expand(input) {
  var output = {};
  var key;
  for (key in input) {
    output[key] = typeof input[key] === 'number' ? [input[key]] : input[key];
  }
  return output;
}
```
