### ISSUE TITLE
Use preset programatically?

### ISSUE THREAD

**Issue by sebastienbarre** [wooorm/remark-lint#99]
Is there a way to use a preset programmatically, as an option to `use(lint)`?

```
const lint_options = {
  presets: [
    'remark-preset-lint-recommended',
  ],
  'no-duplicate-headings': true,
};

unified()
  .use(markdown)
  .use(stringify)
  .use(lint, lint_options)
...
```
the above didn't work. This below seems to work, but I was wondering if this is the intended use.
```
const presetRecommended = require('remark-preset-lint-recommended');
const lint_options = Object.assign({}, presetRecommended.plugins.lint, {
  'no-duplicate-headings': true,
});

unified()
  .use(markdown)
  .use(stringify)
  .use(lint, lint_options)
```

**Comment by wooorm** [comment]
No, unfortunately not. Presets and plugins operate on whole other levels making that quite impossible :(

For now, use the latter method (or define your own style). I’ve got some very early ideas for the future but don’t wait for those!
